language: python

python:
  - "2.7"
  - "3.6"

install:
  - ./.travis/install.sh

script:
  - python test.py

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.2
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.10
